# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1377cf39286dbd02543e622d4273918b20084f8f254a8f40875d5f56bdabbb3c4c012c9565b64cb26945d624e7ab11123e77be4ebe2f80e145a3ce47682d6ab7

test:
  secret_key_base: db60d90825dc8d8f0342eb5041e1c4259c927c06bc920a97f20a894fa5226cb33e8d3d7cd45721c1f409b5074e839f1a9b63baf6efb9cbc1d19ba5bbf69be8d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
